1. 기본 파이썬

In [1]:
# Pandas 라이브러리 불러오기
import pandas as pd

# Numpy 라이브러리 불러오기
import numpy as np

In [2]:
# 숫자 변수 생성
a = 1      # 정수값을 가진 변수 생성
b = 2.3    # 실수값을 가진 변수 생성
c = 3.2E10 # 지수 표현 방법으로 변수 생성
           # 결과는 괄호안의 값과 같다 (3.2 * 10^10)

# 문자열 변수 생성
d = '문자열1' # 작은 따옴표로 표현가능
e = "문자열2" # 큰 따옴표로 표현가능
# 참고 : 문자열 안에 작은따옴표나 큰따옴표가 있다면, 전체를 감싸는 따옴표는 반대되는 것을 사용하여 작성한다

# 줄바꿈 후 출력 - print(    , sep='\n') / print( ' \n ' )
# 참고 : print( ) 괄호 속에는 모두 같은 타입의 값이 입력되야한다.
# ex) print(12 + 34) - 정상출력
# ex) print(1 + '가') - 에러발생
print(d, e, sep='\n') # 각 변수에 대한 결과값을 줄 바꿈 후 출력
print('d\ne') # 문자열 안에서 \n을 활용하여 줄바꿈
print(1, end='') # 출력 후 다음 값이 바로 뒤에서 출력
print(2)
print(d+e) # 문자열변수끼리 덧셈 가능
print(d*2) # 문자열변수 곱셈 가능

# print 기본 옵션 - 줄바꿈 후 출력
print(d, e, sep='\n') # 각 변수에 대한 결과값을 줄 바꿈 후 출력
print('d\ne') # 문자열 안에서 \n을 활용하여 줄바꿈
print(1, end='') # 출력 후 다음 값이 바로 뒤에서 출력
print(2)

문자열1
문자열2
d
e
12
문자열1문자열2
문자열1문자열1
문자열1
문자열2
d
e
12


In [36]:
# 문자열 속 변수 설정
wo = "맛있는"
print("나는 %s 사과를 먹었다." %wo) # 문자열 변수를 print 안에 적용
print("나는 %s 사과를 먹었다." %'맛있는') # 다른 표현 방법 1
print("나는 {} 사과를 먹었다.\n".format('맛있는')) # 다른 표현 방법 2

count = 98
print("Error is %d %%."%count) # 숫자 변수를 print 안에 적용
print("Error is %d %%." % 98) # 다른 표현 방법 1 (""안에서 '%변수'사용 후 '%'를 표현하기 위해서 '%%'를 사용)
print("Error is {} %.\n".format(98)) # 다른 표현 방법 2

number = 10
day = "there"
print ("I ate %d apples. so I was sick for %s days."%(number, day)) # 문자열, 숫자 모두 사용 (순서 중요)
print ("I ate "+str(number)+" apples. so I was sick for "+day+" days.") # 다른 표현 방법 1
# 참고 : print 안은 문자열로 구성되어있기에 숫자변수(number)를 표현할때는 str으로 타입전환을 해야 출력됨
print ("I ate {} apples. so I was sick for {} days.".format(10, 'there')) # 다른 표현 방법 2
# 참고 : 위 문장에서 format에 변수를 하나만 입력할 경우 오류 발생
# format 안의 값은 하나밖에 없는데 지정되지 않은 두 개의 값을 출력하라는 명령어에 오류가 발생함
print ("I ate {1} apples. so I was sick for {0} days.".format('there', 10)) # 다른 표현 방법 3
print ("I ate {} apples. so I was sick for {day} days.\n".format(10, day= 'there')) # 다른 표현 방법 4

나는 맛있는 사과를 먹었다.
나는 맛있는 사과를 먹었다.
나는 맛있는 사과를 먹었다.

Error is 98 %.
Error is 98 %.
Error is 98 %.

I ate 10 apples. so I was sick for there days.
I ate 10 apples. so I was sick for there days.
I ate 10 apples. so I was sick for there days.
I ate 10 apples. so I was sick for there days.
I ate 10 apples. so I was sick for there days.



In [3]:
# 리스트 - a = [  ,  ,  ,  ]
print('리스트 기본 명령어')
a = [1,2,3,['a','b','c']]
print(a[0])
print(a[1])
print(a[3][1])
print(a[-1])
print(len(a))
print(a*2)
print(len(a*3))
print(len(a[3]))
print(a[0:2])
print(a[1:])

print('\n리스트 내용 수정')
b = ['가','나','다']
b[2] = 3
print(b)

print('\n리스트 내용 삭제 - del')
c = [1,2,3,4,5]
print(c)
del c[1] # 리스트 2번째 값을 지움
print(c)
del c[1]
# 참고 : 위에서 지웠기에 세번째에 위치한 값이 두번째로 당겨짐
# 즉 print(b[2]) 입력시 오류 발생
print(c)
del c[1:] # 2번째부터 모두 지움
print(c)

리스트 기본 명령어
1
2
b
['a', 'b', 'c']
4
[1, 2, 3, ['a', 'b', 'c'], 1, 2, 3, ['a', 'b', 'c']]
12
3
[1, 2]
[2, 3, ['a', 'b', 'c']]

리스트 내용 수정
['가', '나', 3]

리스트 내용 삭제 - del
[1, 2, 3, 4, 5]
[1, 3, 4, 5]
[1, 4, 5]
[1]


In [4]:
# 리스트 기능
print('리스트 내용 정렬 1 - sort ( )')
a = [5,8,6,4,2,6,8,4]
print(a)
a.sort()
print(a)

print('\n리스트 내용 정렬 2 - reverse ( )')
a.reverse()
print(a)

print('\n리스트 for 문')
odds = [1, 3, 5, 7, 9]
count = 1

for odd in odds:
  print (count, end=' / ')
  print (odd)
  print ("======")
  count = count +1

리스트 내용 정렬 1 - sort ( )
[5, 8, 6, 4, 2, 6, 8, 4]
[2, 4, 4, 5, 6, 6, 8, 8]

리스트 내용 정렬 2 - reverse ( )
[8, 8, 6, 6, 5, 4, 4, 2]

리스트 for 문
1 / 1
2 / 3
3 / 5
4 / 7
5 / 9


In [36]:
# 문자열 띄어쓰기 - ( ' % 숫자 s ' % ' 문자열 ' )
print("%15s"%"ee")
print("%-15s"%"ee")
print("%-10sjane."%"hi")

             ee
ee             
hi        jane.


In [4]:
# 문자열 찾기
print('문자열 찾기 - a.count( "  " ) / a.index( "  " )')
a = "Life is to short"
print(a.count('b')) # 문자열 중 'b'의 갯수를 출력
print(a.count('i')) # 문자열 중 'i'의 갯수를 출력
print(a.index('t')) # 문자열 중 't'가 가장 처음으로 나온 위치값 출력 (없으면 오류 발생)
print(a.index('L')) # 문자열 중 'L'이 가장 처음으로 나온 위치값 출력

# 문자열 분리 - a.split( ' ' )
print('\n문자열 분리 - a.split( " " )')
print(a.split()) # 띄어쓰기를 기준으로 문자열 분리
b = 'a:b:c:d,e:f'
print(b.split(':')) # 특정 기호를 기준으로 문자열 분리
print(b.split(','))

문자열 찾기 - a.count( "  " ) / a.index( "  " )
0
2
8
0

문자열 분리 - a.split( " " )
['Life', 'is', 'to', 'short']
['a', 'b', 'c', 'd,e', 'f']
['a:b:c:d', 'e:f']


In [10]:
# 리스트 기능
print('리스트 내용 삽입 - " ".join ( a )')
list = ['a', 'b', 'c', 'd']
result1 = "#".join(list)
result2 = "$".join(['e','f','g','f'])
print(result1)
print(result2)

print('\n리스트 특정 문자 제거 - a.remove ( )')
a = [1,2,3,1,'가',2,3,'가']
print(a)
a.remove(3) # 처음 오는 3 제거
print(a)
a.remove('가') # 처음 오는 '가' 제거
print(a)

print('\n리스트 특정 문자 추출 - a.pop ( )')
b = [1,2,3,'가','나','다']
print(b)
c = b.pop(3) # 리스트 4번째 값을 추출
print(c)
print(b) # 위에서 추출되었기에 '가'는 리스트에서 없어짐


리스트 내용 삽입 - " ".join ( a )
a#b#c#d
e$f$g$f

리스트 특정 문자 제거 - a.remove ( )
[1, 2, 3, 1, '가', 2, 3, '가']
[1, 2, 1, '가', 2, 3, '가']
[1, 2, 1, 2, 3, '가']

리스트 특정 문자 추출 - a.pop ( )
[1, 2, 3, '가', '나', '다']
가
[1, 2, 3, '나', '다']


In [2]:
# 임의의 데이터 프레임 만들기
df1 = pd.DataFrame(dict(time = np.arange(4), value = np.random.randn(4)))
print(df1)

print('\n행 추가')
df1['value2'] = np.arange(4)
print(df1)

print('\n행 합계 추가 - df[ ' ' ] = df.sum(axis = 1)')
df1['sum'] = df1.sum(axis = 1)
print(df1)

print('\n열 합계 추가 - df.loc[ ' ' ] = df.sum(axis = 0)')
df1.loc['sum2'] = df1.sum(axis = 0)
print(df1)

   time     value
0     0  0.162869
1     1  0.243119
2     2  0.986608
3     3  1.259104

행 추가
   time     value  value2
0     0  0.162869       0
1     1  0.243119       1
2     2  0.986608       2
3     3  1.259104       3

행 합계 추가 - df[  ] = df.sum(axis = 1)
   time     value  value2       sum
0     0  0.162869       0  0.162869
1     1  0.243119       1  2.243119
2     2  0.986608       2  4.986608
3     3  1.259104       3  7.259104

열 합계 추가 - df.loc[  ] = df.sum(axis = 0)
      time     value  value2        sum
0      0.0  0.162869     0.0   0.162869
1      1.0  0.243119     1.0   2.243119
2      2.0  0.986608     2.0   4.986608
3      3.0  1.259104     3.0   7.259104
sum2   6.0  2.651699     6.0  14.651699


In [3]:
# 튜플
t1 = (1,2,3) # 대괄호가 아닌 소괄호로 튜플 정의 (수정 안됨)
print(t1)

(1, 2, 3)


In [8]:
# 딕셔너리
print('딕셔너리 만들기')
dictionary = {1: 'a', 4: 'b', 'name': 'pey', 3: [1, 2, 3]}
print(dictionary)
print(dictionary.keys()) # key값 출력
print(dictionary.values()) # value값 출력
print ("===========")
dictionary[2] = 'c' # 현재 딕셔너리에 없는 값을 넣게 되면 자동적으로 추가하게 된다. 
print(dictionary)
# 참고 : 리스트에서 a[1]은 리스트 값 중 두번째 값을 의미한다.

print('\n중복된 key값 넣기 - a[4] = "b" -> "c"')
a[4] = 'c' # 중복된 값을 넣게 되면 이전에 입력된 값은 삭제된다.
print(a)

print('\n딕셔너리 요소 제거 - del a[ ]')
del a[4] # key, value값 제거
print(a)

print('\n딕셔너리 for문')
for_test = {1: 'a', 2: 'b', 'name': 'mark', 3: [1, 2, 3]}
print(for_test)
for key in for_test.keys() :
    print(key, end=' / ')
    print(for_test[key])

딕셔너리 만들기
{1: 'a', 4: 'b', 'name': 'pey', 3: [1, 2, 3]}
dict_keys([1, 4, 'name', 3])
dict_values(['a', 'b', 'pey', [1, 2, 3]])
{1: 'a', 4: 'b', 'name': 'pey', 3: [1, 2, 3], 2: 'c'}

중복된 key값 넣기 - a[4] = "b" -> "c"
[8, 8, 6, 6, 'c', 4, 4, 2]

딕셔너리 요소 제거 - del a[ ]
[8, 8, 6, 6, 4, 4, 2]

딕셔너리 for문
{1: 'a', 2: 'b', 'name': 'mark', 3: [1, 2, 3]}
1 / a
2 / b
name / mark
3 / [1, 2, 3]


In [6]:
# 집합
s1 = set('helllllllllllllooooooooooo')
print(s1) # 중복된 값 표시 안함
print(s1[0]) # 집합은 순서가 없기에 에러 발생

{'o', 'l', 'e', 'h'}


TypeError: 'set' object is not subscriptable

In [7]:
# 집합 연산
s1 = set ([1,2,3,4,5,6])
s2 = set ([4,5,6,7,8,9])
print('교집합')
s3 = s1&s2
print(s3)

print('\n합집합')
s4 = s1|s2
print(s4)
print(s1.union(s2)) # 합집합과 동일은 값을 출력한다.

print('\n집합 간 뺄셈')
s5 = s1-s2 
print(s5)  # s1에서 s2와의 중복값만 제거된다.

교집합
{4, 5, 6}

합집합
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 6, 7, 8, 9}

집합 간 뺄셈
{1, 2, 3}


In [8]:
# id값 출력
a = [1,2,3]
print(a)
b = a # id(a)값과 id(b)값이 동일하게 설정된다.
print(b)  
print(id(a))
print(id(b))

print('\nid를 다르게 설정하는 방법 2가지 - a.copy() / a[:]')
b = a.copy() # id(a)값과 id(b)값이 다르게 설정된다.
c = a[:] # id(a)값과 id(c)값이 다르게 설정된다.
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[1, 2, 3]
[1, 2, 3]
2029405816384
2029405816384

id를 다르게 설정하는 방법 2가지 - a.copy() / a[:]
[1, 2, 3]
[1, 2, 3]
2029405816384
2029405818496
2029405811072


2. 라이브러리 Numpy

In [22]:
# numpy 라이브러리 불러오기
import numpy as np
print('"0"값을 가지는 리스트 만들기 - np.zeros( a )')
n1 = np.zeros(6) # 5개의 0값을 가지는 리스트
print(n1)

print('\n배열 재정렬 - np.reshape( a , ( n , m ) )')
n2 = np.reshape(n1, (2,3))
print(n2)

print('\n배열 만들기 - np.arange( l ).reshape( n , m )')
n3 = np.arange(9).reshape(3,3)
print(n3)
print()
n4 = np.arange(12).reshape(3,4)
print(n4)


"0"값을 가지는 리스트 만들기 - np.zeros( a )
[0. 0. 0. 0. 0. 0.]

배열 재정렬 - np.reshape( a , ( n , m ) )
[[0. 0. 0.]
 [0. 0. 0.]]

배열 만들기 - np.arange( l ).reshape( n , m )
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
# 넘파이 배열 결합
print('배열 결합(세로) - np.vstack ( ( a , b ) )')
n2n3 = np.vstack((n2,n3))
print(n2n3)

print('\nvstack의 경우 열의 크기가 같아야한다.')
n3n4 = np.vstack((n3,n4))
print(n3n4)


배열 결합(세로) - np.vstack ( ( a , b ) )
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

vstack의 경우 열의 크기가 같아야한다.


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [24]:
print('\n배열 결합(가로) - np.hstack ( ( a , b ) )')
n3n4 = np.hstack((n3,n4))
print(n3n4)

print('\nvstack의 경우 행의 크기가 같아야한다.')
n2n3 = np.hstack((n2,n3))
print(n2n3)


배열 결합(가로) - np.hstack ( ( a , b ) )
[[ 0  1  2  0  1  2  3]
 [ 3  4  5  4  5  6  7]
 [ 6  7  8  8  9 10 11]]

vstack의 경우 행의 크기가 같아야한다.


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

3. 라이브러리 Pandas

In [10]:
# 데이터프레임 (Type : DataFrame())
import pandas as pd

print('"0"값을 가지는 데이터프레임 만들기 - pd.DataFrame()')
rows = 5
columns_1 = 10
df = pd.DataFrame(0, index=range(rows), columns=range(columns_1))
print(df)

print('\nnumpy 라이브러리를 사용하여 위와 같은 형태의 데이터프레임 만들기')
df = pd.DataFrame(np.zeros((5,10)))
print(df)

"0"값을 가지는 데이터프레임 만들기 - pd.DataFrame()
   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0  0

numpy 라이브러리를 사용하여 위와 같은 형태의 데이터프레임 만들기
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0


In [11]:
# 결측값을 포함하는 데이터프레임 생성
df1 = df
df1[0][2] = None
df1[2][0] = None
df1[5][2] = None
df1[5][3] = None
df1[9][4] = None
print(df1)

# 결측치 치환
print('\n결측값 채우기 회수 제한 (fillna(method="ffill", limit=number)')
print(df1.fillna(method = 'ffill', limit = 1)) # 제한을 1로 두어서 [5,3]값이 결측치로 남음
print('---------------------------------------------------')
print(df1.fillna(method = 'bfill', limit = 1)) # 제한을 1로 두어서 [5,2]값이 결측치로 남음
print('---------------------------------------------------')
print(df1.fillna(method = 'bfill', limit = 2)) # 제한을 2로 두어서 [5,2]값이 치환됨


     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  NaN  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN

결측값 채우기 회수 제한 (fillna(method="ffill", limit=number)
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
---------------------------------------------------
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0

4. 데이터프레임

In [24]:
# 데이터프레임 모든 열 출력 - pd.set_option('display.max_columns', None)
pd.options.display.max_columns = 2
print(df1)
pd.set_option('display.max_columns', None)
print(df1)
pd.options.display.max_columns = 20 #기본값
print('----------------------------------------------------\n')

# 데이터프레임 모든 행 출력 - pd.set_option('display.max_rows', None)
pd.options.display.max_rows = 4
print(df1)
pd.set_option('display.max_rows', None)
print(df1)
pd.options.display.max_rows = 60 #기본값

     0  ...    9
0  0.0  ...  0.0
1  0.0  ...  0.0
2  NaN  ...  0.0
3  0.0  ...  0.0
4  0.0  ...  NaN

[5 rows x 10 columns]
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  NaN  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN
----------------------------------------------------

      0    1    2    3    4    5    6    7    8    9
0   0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3   0.0  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN

[5 rows x 10 columns]
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  NaN  0.0 